block_list:
  div:
    class:
      - col-12 col-md-6 col-lg-4 mb-5
  block:
    links_text:
      - a
    title_list_2:
      h2:
        class:
          - card-title h4 my-0 py-0
    links:
      links_text:
        - href
    datetime_list:
      small:
        class:
          - text-muted